server:
  port: 9080

management:
  endpoints:
    web:
      exposure:
        include: prometheus
      base-path: /
  metrics:
    enable:
      # Эти компоненты экспортируют метрики с ключевым словом name, на которое ругается unified-agent
      executor: false
      cache: false

spring:
  cache:
    cache-names: temperature_cache
    caffeine:
      spec: maximumSize=100,expireAfterWrite=15s

bot:
  # Параметры подключения к чатботу.
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  # Пользователи, которые могут писать боту (бот поддерживает только личные диалоги)
  validUserIds: ${BOT_VALID_USER_IDS}
  # Идентификаторы чатов, в которые бот будет слать рассылки
  chatIds: ${BOT_CHAT_IDS}
  # Периодичность запуска таски, которая проверяет статус сессии и пытается переподключиться
  sessionCheckInterval: PT1M

modbus:
  tcpHost: dr302
  tcpPort: 8234
  # Задержка после каждой операции с modbus, иначе устройства не успевают обрабатывать команды
  delay: 50

temperature:
  # Периодичность расчета необходимости отопления в доме
  controlInterval: PT1M
  # Целевая температура в доме
  insideTarget: 23
  # Температура на улице, при повышении до которой отопление должно отключаться
  outsideMax: 20
  # Отопление отключатся при повышении температуры на улице выше целевой в доме, а включаются при опускании уличной на гистерезис от заданной
  hysteresis: 3
  # Самая холодная расчетная температура на улице
  outsideMin: -30

# Настройки опроса плат опроса датчиков DS18B20, модель R4DCB08
temperatureSensorsBoard:
  # плата 1
  board1:
    # modbus slaveId
    address: 1
  # Настройки регистров температурных сенсоров находятся в enum TemperatureSensorsPresets

# Настройки управления газовым котлом
gasBoiler:
  # Настройки управления реле газового котла
  relay:
    # Modbus slaveId
    address: 2
    # Coil в который пишется значение (F05), нумерация с 0
    coil: 0
    # Периодичность запуска таски управления реле (она фактически включает и выключает реле котла)
    controlInterval: PT15S
  # Периодичность опроса подачи газового котла (в отопление), чтобы понимать его статус
  direct:
    pollInterval: PT15S
  # Набор температур для расчета целевой температуры обратки для включения газового котла в зависимости от температуры на улице
  temperature:
    # Минимальная разница между подачей и обраткой при которой котел считается работающим
    turnOnMinDelta: 1
    # Падение температуры подачи от максимальной за период при которой котел считается отключившимся
    turnOffDirectDelta: 5
    # Интервал допустимых температур подачи по которым считается целевая температура котла
    direct:
      min: 30
      max: 71
      # До какого процента от рассчитанной целевой температуры должна разогреться подача из котла чтобы можно было считать что котел отключится по достижению целевой подачи
      maxPercent: 85
    # Интервал допустимых температур обратки из которых берется температура для включения котла
    return:
      min: 25
      max: 45
    # Температурный интервал выбранной кривой погодозависимой автоматики котла, сейчас выбрана кривая N20
    weatherCurve:
      min: -20
      max: 15
  # Объем воды проходящий через котел в режиме отопления (м3/ч)
  waterFlow: 1.23

# Настройки управления электрическим котлом
electricBoiler:
  # Настройки управления реле электрического котла
  relay:
    # Modbus slaveId
    address: 3
    # Coil в который пишется значение (F05), нумерация с 0
    coil: 0
  # Периодичность опроса температуры в котельной для управления электрокотлом
  controlInterval: PT5M
  # Электрокотел включается при опускании температуры в котельной меньше минимальной, а отключается при поднятии на гистерезис от минимальной
  hysteresis: 1

# Настройки управления теплым полом
floorHeating:
  # Периодичность запуска управления теплым полом (интервал не должен быть меньше чем 2 rotationTime + 2 rotationTimeDelay)
  controlInterval: PT2M
  temperature:
    # Максимальная температура подачи в теплый пол
    direct:
      max: 45
    # Максимальная дельта между обраткой и целевой подачей (ограничивает открытие клапана, иначе в котел пойдет слишком холодная обратка)
    maxDelta: 8
    # Точность температуры подачи (в градусах), которую должен выдерживать сервопривод клапана
    accuracy: 2
    # Коэффициент изолированности, определяет влияние разницы между целевой температурой в помещении и на улице на целевую температуру подачи
    k: 0.35
  # Настройки клапана подмеса
  valve:
    # Реле управляющее питанием сервопривода клапана
    relay:
      # Modbus slaveId
      address: 4
      # Coil в который пишется значение (F05), нумерация с 0
      coil: 1
      # Расчетное время полного оборота клапана (секунд)
      rotationTime: 45
      # Запас по времени на каждую операцию с клапаном (секунд)
      rotationTimeReserve: 5
    # Цифро-аналоговый преобразователь
    dac:
      # Modbus slaveId
      address: 5
      # Регистр, из которого читается и в который пишется значение (F03, F06)
      register: 1
      # Точность установки сервопривода клапана (в процентах)
      accuracy: 3
      # Максимальное значение, на которое увеличивается процент открытия за один шаг, чтобы котел не встал по холодной обратке
      maxIncreaseStep: 5
      # Минимальный процент открытия клапана
      # (он нужен, потому что если клапан закрыт совсем - температура подачи до смешения в теплые полы будет очень низкая и невозможно будет управлять теплым полом)
      minOpenPercent: 10
      # Максимальный процент открытия клапана (чтоб котел не обливался холодной обраткой)
      maxOpenPercent: 70

# Реле управляющее питанием насосов отопления
heatingPumps:
  relay:
    # Modbus slaveId
    address: 4
    # Coil в который пишется значение (F05), нумерация с 0
    coil: 0
    # Периодичность запуска таски управления реле (она фактически включает и выключает реле насосов)
    controlInterval: PT5M

# Настройки управления уличным освещением
streetLight:
  # Настройки реле, управляющего освещением
  relay:
    # Modbus slaveId
    address: 3
    # Coil в который пишется значение (F05), нумерация с 0
    coil: 1
  # Периодичность расчета необходимости освещения
  controlInterval: PT5M
  # Широта и долгота места, для которого рассчитывается время суток
  latitude: ${LATITUDE}
  longitude: ${LONGITUDE}

# Настройки управления обогрева воронок
funnelHeating:
  # Настройки реле, управляющего обогревом
  relay:
    # Modbus slaveId
    address: 2
    # Coil в который пишется значение (F05), нумерация с 0
    coil: 1
  # Периодичность расчета необходимости обогрева
  controlInterval: PT15M
  # Пороговые значения температуры между которыми включается обогрев
  temperature:
    min: -2.0
    max: 2.0

# Настройки опроса напряжения на входе в ИБП
cityPowerInput:
  relay:
    # Modbus slaveId
    address: 2
    # DiscreteInput к которому подключено реле электрической линии города
    discreteInput: 0
  # Периодичность опросов напряжения на входе в ИБП
  controlInterval: PT1M

health:
  # Периодичность опросов селфмониторинга (проверки по аварийным событиям сервиса HealthService и критичных температур)
  controlInterval: PT15M

logging:
  config: classpath:log4j2.yml
